name: Build and Deploy Blockly Robotech
on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # Pozwala uruchomić budowanie ręcznie przyciskiem

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Dependencies
        run: |
          # Pobieranie niezbędnych bibliotek Blockly
          python3 make.py deps

      - name: Build Maze
        run: |
          # Kompilacja gry Maze
          python3 make.py maze

      - name: Upload Artifacts
          # Używamy najnowszej wersji v4 dla artefaktów
        uses: actions/upload-artifact@v4
        with:
          name: blockly-games-build
          path: appengine/
