name: Build and Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y subversion python2-minimal default-jre
          sudo ln -sf /usr/bin/python2 /usr/bin/python

      - name: Build
        run: |
          make deps || true
          make maze-pl

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./appengine
