name: Build and Deploy
on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    # Używamy gotowego kontenera ze starym Debianem, który ma wszystko czego potrzebujesz
    container:
      image: python:2.7-slim-buster

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: |
          apt-get update
          # Instalujemy SVN i Javę (niezbędna do kompilatora Closure)
          apt-get install -y subversion default-jre-headless
          # W tym kontenerze 'python' to już wersja 2.7, więc nie trzeba aliasów

      - name: Build Maze
        run: |
          make deps || echo "Ignoruję błędy SVN"
          make maze-pl

      - name: Deploy
        # Musimy wyjść z kontenera, żeby użyć akcji Deploy (ona wymaga nowszego Node.js)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./appengine
          force_orphan: true
